### ISSUE TITLE
Add support package with version containing a wildcard (i.e. 3.*)

### ISSUE THREAD

**Issue by pmiossec** [spectresystems/snitch#2]
For the moment, the tool fails with the error:

```
Analysing project MyProject...

Building MyProject (net471)...

Error: Version '3.*' is not valid. (Parameter 'version')
```

**Comment by patriksvensson** [comment]
@pmiossec Absolutely. This is a scenario I haven't encountered personally, but would absolutely be nice to have.

**Comment by glennawatson** [comment]
This one is hitting me at the moment, do you want me to have a look at doing a PR for you @patriksvensson

**Comment by patriksvensson** [comment]
@glennawatson Sure! I suspect you will need to implement a custom semver representation and comparer since the current one doesn't support wildcards, but would appreciate the PR!

**Comment by pmiossec** [comment]
I'm looking forward to see this issue fixed as it prevents me to use it on my project.

Thanks in advance for the effort!

**Comment by augustoproiete** [comment]
I've just got hit but this one as well:

```bash
Error: Version '3.3.102.*' for package 'AWSSDK.SecretsManager' is not valid. (Parameter 'version')
```

Is there a workaround to just tell it to keep going and ignore the error?

@glennawatson / @patriksvensson are you still planning on working on this one? If not I could look into it

**Comment by patriksvensson** [comment]
@pmiossec @glennawatson @augustoproiete This have been fixed in version 1.8.0 of Snitch (should be available on NuGet shortly)

**Comment by augustoproiete** [comment]
Thanks a lot @jmarolf & @patriksvensson! Works like a charm  🚀

**Comment by laurentAstonIf** [comment]
Hello
I'm still getting the error from the last version or source code
'Could not find color or style '2.4.1,3.0.0)[/'.'

reason contains [grey]Might be updated from[/] [silver][2.4.1,3.0.0)[/] [grey]in[/] [aqua]Aston.Testing[/]
